### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Wang-pengfei** [chengzhag/PanFusion#3]
Hi, I noticed that you mentioned, "The training takes about 7 hours on 4x NVIDIA A100 GPU." However, when I ran the training without making any code changes, I found that each epoch took close to 2 hours. Do you know what could be causing this? Or could you provide me with a training log file to help me identify the issue?

**Comment by chengzhag** [comment]
Hi @Wang-pengfei, we updated links to wandb log in ec794ef9564df077ca2d67d0148925ab4332cd93. You can compare your GPU Usage to identify the issue. During the training stage, our usage is around 80%.

![image](https://github.com/chengzhag/PanFusion/assets/9084912/6c17a564-5834-43e6-8182-be2dcc9b22f7)

**Comment by Wang-pengfei** [comment]
Thanks！
